
x-mysql-env: &mysql-env
  MYSQL_USER: lucky
  MYSQL_PASSWORD: Ling@1603
  MYSQL_ROOT_PASSWORD: Ling@1603

x-mysql-health: &mysql-health
  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  interval: 10s
  timeout: 5s
  retries: 5

x-cassandra-env: &cassandra-env
  CASSANDRA_DC: "DC1"
  CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

x-cassandra-health: &cassandra-health
  test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
  interval: 20s
  timeout: 10s
  retries: 5

x-postgres-env: &postgres-env
  POSTGRES_USER: lucky
  POSTGRES_PASSWORD: Ling@1603

x-postgres-health: &postgres-health
  test: ["CMD-SHELL", "pg_isready -U lucky"]
  interval: 10s
  timeout: 5s
  retries: 5

services:

  mysql-cart-qa:
    image: mysql:8.0
    container_name: mysql-cart-qa
    restart: always
    environment:
      <<: *mysql-env
      MYSQL_DATABASE: card-qa
    ports:
      - "3309:3306"
    healthcheck: *mysql-health

  cassandra-product-qa:
    image: cassandra:4.1
    container_name: cassandra-product-qa
    restart: always
    environment:
      <<: *cassandra-env
      CASSANDRA_CLUSTER_NAME: "QA Cluster"
    ports:
      - "9044:9042"
    healthcheck: *cassandra-health

  postgres-wishlist-qa:
    image: postgres:15
    container_name: postgres-wishlist-qa
    restart: always
    environment:
      <<: *postgres-env
      POSTGRES_DB: wishlist_qa
    ports:
      - "5435:5432"
    healthcheck: *postgres-health
