spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI:https://github.com/linkelumalai/ecom-config}
          skip-ssl-validation: false
		  timeout: 5

#server configuration
server:
  port: 8081
  
