spring:
  datasource:
    url: jdbc:mysql://${QA_DB_HOST:localhost}:${QA_DB_PORT:3309}/${QA_DB_NAME:card-qa}
    username: ${QA_DB_USERNAME:lucky}
    password: ${QA_DB_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${QA_DB_MAX_POOL_SIZE:10}
      minimum-idle: ${QA_DB_MIN_IDLE:2}
      idle-timeout: ${QA_DB_IDLE_TIMEOUT:30000}
      pool-name: ${QA_DB_POOL_NAME:CartHikariCP-QA}

  jpa:
    hibernate:
      ddl-auto: ${QA_HIBERNATE_DDL:validate}
    show-sql: ${QA_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${QA_HIBERNATE_FORMAT_SQL:false}

server:
  port: ${QA_SERVER_PORT:9990}

logging:
  level:
    root: ${QA_LOG_LEVEL_ROOT:INFO}
    org.springframework: ${QA_LOG_LEVEL_SPRING:INFO}
    com.yourcompany.cart: ${QA_LOG_LEVEL_CART:INFO}
