spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST:prod-db-host}:${PROD_DB_PORT:3308}/${PROD_DB_NAME:card-prod}
    username: ${PROD_DB_USERNAME:lucky}
    password: ${PROD_DB_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${PROD_DB_MAX_POOL_SIZE:20}
      minimum-idle: ${PROD_DB_MIN_IDLE:5}
      idle-timeout: ${PROD_DB_IDLE_TIMEOUT:60000}
      pool-name: ${PROD_DB_POOL_NAME:CartHikariCP-Prod}

  jpa:
    hibernate:
      ddl-auto: ${PROD_HIBERNATE_DDL:validate}
    show-sql: ${PROD_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${PROD_HIBERNATE_FORMAT_SQL:false}

server:
  port: ${PROD_SERVER_PORT:9900}

logging:
  level:
    root: ${PROD_LOG_LEVEL_ROOT:WARN}
    org.springframework: ${PROD_LOG_LEVEL_SPRING:WARN}
    com.yourcompany.cart: ${PROD_LOG_LEVEL_CART:INFO}
