spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:card-dev}
    username: ${DB_USERNAME:lucky}
    password: ${DB_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      pool-name: ${DB_POOL_NAME:CartHikariCP}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  devtools:
    restart:
      enabled: ${DEVTOOLS_RESTART:true}

  output:
    ansi:
      enabled: ${ANSI_ENABLED:ALWAYS}

server:
  port: ${SERVER_PORT:9000}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    com.yourcompany.cart: ${LOG_LEVEL_CART:DEBUG}
