spring:
  data:
    cassandra:
      contact-points: ${QA_CASSANDRA_HOST:localhost}
      port: ${QA_CASSANDRA_PORT:9044}
      keyspace-name: ${QA_CASSANDRA_KEYSPACE:product_qa_keyspace}
      username: ${QA_CASSANDRA_USERNAME:lucky}
      password: ${QA_CASSANDRA_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
      schema-action: ${QA_CASSANDRA_SCHEMA_ACTION:validate}

server:
  port: ${QA_SERVER_PORT:9991}

logging:
  level:
    root: ${QA_LOG_LEVEL_ROOT:INFO}
    org.springframework: ${QA_LOG_LEVEL_SPRING:INFO}
    com.yourcompany.product: ${QA_LOG_LEVEL_PRODUCT:INFO}
