spring:
  datasource:
    url: jdbc:postgresql://${DEV_PG_HOST:localhost}:${DEV_PG_PORT:5433}/${DEV_PG_DB:wishlist_dev}
    username: ${DEV_PG_USER:lucky}
    password: ${DEV_PG_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DEV_PG_POOL_SIZE:10}
      minimum-idle: ${DEV_PG_MIN_IDLE:2}
      idle-timeout: ${DEV_PG_IDLE_TIMEOUT:30000}
      pool-name: ${DEV_PG_POOL_NAME:WishlistHikariCP}

  jpa:
    hibernate:
      ddl-auto: ${DEV_HIBERNATE_DDL:update}
    show-sql: ${DEV_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${DEV_HIBERNATE_FORMAT_SQL:true}

server:
  port: ${DEV_SERVER_PORT:9002}

logging:
  level:
    root: ${DEV_LOG_LEVEL_ROOT:INFO}
    org.springframework: ${DEV_LOG_LEVEL_SPRING:INFO}
    com.yourcompany.wishlist: ${DEV_LOG_LEVEL_WISHLIST:DEBUG}
