spring:
  datasource:
    url: jdbc:postgresql://${QA_PG_HOST:localhost}:${QA_PG_PORT:5435}/${QA_PG_DB:wishlist_qa}
    username: ${QA_PG_USER:lucky}
    password: ${QA_PG_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${QA_PG_POOL_SIZE:10}
      minimum-idle: ${QA_PG_MIN_IDLE:2}
      idle-timeout: ${QA_PG_IDLE_TIMEOUT:30000}
      pool-name: ${QA_PG_POOL_NAME:WishlistHikariCP-QA}

  jpa:
    hibernate:
      ddl-auto: ${QA_HIBERNATE_DDL:validate}
    show-sql: ${QA_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${QA_HIBERNATE_FORMAT_SQL:false}

server:
  port: ${QA_SERVER_PORT:9992}

logging:
  level:
    root: ${QA_LOG_LEVEL_ROOT:INFO}
    org.springframework: ${QA_LOG_LEVEL_SPRING:INFO}
    com.yourcompany.wishlist: ${QA_LOG_LEVEL_WISHLIST:INFO}
