spring:
  datasource:
    url: jdbc:postgresql://${PROD_PG_HOST:prod-db}:${PROD_PG_PORT:5434}/${PROD_PG_DB:wishlist_prod}
    username: ${PROD_PG_USER:lucky}
    password: ${PROD_PG_PASSWORD:{cipher}6cbbbf9d58349ac6990495b827cdd272e26d77b510be1aee9cfa33f130c15175}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${PROD_PG_POOL_SIZE:20}
      minimum-idle: ${PROD_PG_MIN_IDLE:5}
      idle-timeout: ${PROD_PG_IDLE_TIMEOUT:60000}
      pool-name: ${PROD_PG_POOL_NAME:WishlistHikariCP-Prod}

  jpa:
    hibernate:
      ddl-auto: ${PROD_HIBERNATE_DDL:validate}
    show-sql: ${PROD_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${PROD_HIBERNATE_FORMAT_SQL:false}

server:
  port: ${PROD_SERVER_PORT:9902}

logging:
  level:
    root: ${PROD_LOG_LEVEL_ROOT:WARN}
    org.springframework: ${PROD_LOG_LEVEL_SPRING:WARN}
    com.yourcompany.wishlist: ${PROD_LOG_LEVEL_WISHLIST:INFO}
